// createserverwindow.h
// -*- encoding: utf-8 -*-
// @Author: RZH

#ifndef ARMYCHESS_CREATESERVERWINDOW_H
#define ARMYCHESS_CREATESERVERWINDOW_H

#include <QDialog>

#include "mainwindow.h"

QT_BEGIN_NAMESPACE
namespace Ui { class createServerWindow; }
QT_END_NAMESPACE

class createServerWindow : public QDialog {
Q_OBJECT

public:
    /**
     * constructor
     * @param parent parent widget
     * @param ip host ip address
     * @param state connection state
     */
    explicit createServerWindow(QWidget *parent = nullptr, const QString& ip = "",
                                int state = LISTENING);

    ~createServerWindow() override;

    /**
     * set display information
     * @param status connection state
     */
    void setInfo(int status);

private:
    Ui::createServerWindow *ui;  // ui generated by .ui file
    QString ip_;  // host ip address
};


#endif //ARMYCHESS_CREATESERVERWINDOW_H
